version: 1.3.3.{build}
configuration: Release
platform: Any CPU 
before_build:
  - nuget restore
build:
  project: MabiPacker.sln
  verbosity: minimal
artifacts:
- path: \bin\Release\*
  name: MabiPacker.$(GitVersion_LegacySemVerPadded)
  type: zip
