version: 2.0.0.{build}
max_jobs: 2
environment: EnableNuGetPackageRestore: true
configuration: Release
platform: x86
build:
  project: MabiPacker.sln
  verbosity: minimal
before_build:
- cmd: nuget restore -Verbosity quiet
after_build:
- cmd: git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%\gitshort.txt
- cmd: set /P GITSHORT=<%TMP%\gitshort.txt
- set BUILD_ARCHIVE="%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%PLATFORM%-%CONFIGURATION%.7z"
- cmd: cd "MabiPack\MabiPacker\bin\%CONFIGURATION%"
- cmd: 7z a %BUILD_ARCHIVE% * -xr!.gitignore
- appveyor PushArtifact %BUILD_ARCHIVE%
- cmd: cd ..\..\..\..
