//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MabiPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MabiPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About MabiPacker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_About {
            get {
                return ResourceManager.GetString("Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Hint {
            get {
                return ResourceManager.GetString("Button_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Pack {
            get {
                return ResourceManager.GetString("Button_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Unpack {
            get {
                return ResourceManager.GetString("Button_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ViewContent {
            get {
                return ResourceManager.GetString("Button_ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Visit {
            get {
                return ResourceManager.GetString("Button_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Copression Level: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose data directory for packing: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_PackDistination {
            get {
                return ResourceManager.GetString("Label_PackDistination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_PackFileName {
            get {
                return ResourceManager.GetString("Label_PackFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose distination of unpacked files directory: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_UnpackDistination {
            get {
                return ResourceManager.GetString("Label_UnpackDistination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select *.pack file to unpack: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_UnpackFile {
            get {
                return ResourceManager.GetString("Label_UnpackFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Operation is finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Finish {
            get {
                return ResourceManager.GetString("String_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify a value larger than the client version.
        ///Also, the generated * .pack file should be flagged as “read only” to prevent it from being deleted during startup checks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Hint {
            get {
                return ResourceManager.GetString("String_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Initializing {
            get {
                return ResourceManager.GetString("String_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation is interrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Interrupted {
            get {
                return ResourceManager.GetString("String_Interrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mabinogi Package File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_PackFileDesciption {
            get {
                return ResourceManager.GetString("String_PackFileDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Packing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Packing {
            get {
                return ResourceManager.GetString("String_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select extracted file destination. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_SetExportTo {
            get {
                return ResourceManager.GetString("String_SetExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select directory to pack. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_SetPackDistination {
            get {
                return ResourceManager.GetString("String_SetPackDistination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a file name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_SetPackFileName {
            get {
                return ResourceManager.GetString("String_SetPackFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This program has been terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_TarminateMessageContent {
            get {
                return ResourceManager.GetString("String_TarminateMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This program is terminating.
        ///Do you want to display information about this problem? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_TarminateMessageContentOutput {
            get {
                return ResourceManager.GetString("String_TarminateMessageContentOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A problem caused this program to stop working. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_TarminateMessageMain {
            get {
                return ResourceManager.GetString("String_TarminateMessageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Unpacking... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Unpacking {
            get {
                return ResourceManager.GetString("String_Unpacking", resourceCulture);
            }
        }
    }
}
