//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MabiPacker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MabiPacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Work will be started.
        ///Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Confirm {
            get {
                return ResourceManager.GetString("Str_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory you entered does not exist.
        ///Please check data directory value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_DataDirNotExists {
            get {
                return ResourceManager.GetString("Str_DataDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work is done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Done {
            get {
                return ResourceManager.GetString("Str_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Finish {
            get {
                return ResourceManager.GetString("Str_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Initialize {
            get {
                return ResourceManager.GetString("Str_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is exists. Overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Overwrite {
            get {
                return ResourceManager.GetString("Str_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Pack {
            get {
                return ResourceManager.GetString("Str_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now Packing... Please take for few minutes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Packing {
            get {
                return ResourceManager.GetString("Str_Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Unpack {
            get {
                return ResourceManager.GetString("Str_Unpack", resourceCulture);
            }
        }
    }
}
